### ISSUE TITLE
Add liveness and readiness probes

### ISSUE THREAD

**Issue by karthiknagraj** [toughnoah/elastalert-operator#70]
How can I configure liveness and readiness probes for elastalert-operator. Since we do not have any rest APIs to query for and also the port at which to listen. How can this be done ?

**Comment by toughnoah** [comment]
Sorry for that late.  As the defualt listening port is 8081, can you try this inside the pod?
curl localhost:8081/healthz 
curl localhost:8081/readyz

**Comment by toughnoah** [comment]
> How can I configure liveness and readiness probes for elastalert-operator. Since we do not have any rest APIs to query for and also the port at which to listen. How can this be done ?

Sorry for that late. As the defualt listening port is 8081, can you try this inside the pod?
curl localhost:8081/healthz
curl localhost:8081/readyz

**Comment by toughnoah** [comment]
> How can I configure liveness and readiness probes for elastalert-operator. Since we do not have any rest APIs to query for and also the port at which to listen. How can this be done ?

Sorry for that late. As the default listening port is 8081, can you try this inside the pod?
curl localhost:8081/healthz
curl localhost:8081/readyz

**Comment by toughnoah** [comment]
> How can I configure liveness and readiness probes for elastalert-operator. Since we do not have any rest APIs to query for and also the port at which to listen. How can this be done ?

Sorry for that late. As the defualt health-probe-bind-address port is 8081, can you try this?
liveness  :8081/healthz
readiness  :8081/readyz

and metrics path is :8080/metrics
